name: PluginJam
version: '${version}'
main: com.pluginjam.PluginJam
api-version: 1.19
authors: [ HiWhatName, earomc ]
softdepend: [NoteBlockAPI]
depend: [FastAsyncWorldEdit]
description: The more you have, the worse it is
website: https://www.youtube.com/watch?v=dQw4w9WgXcQ
commands:
  gendungeon:
    description: Used for testing purposes only
    usage: /<command>
  toggleradio:
    description: Toggles the radio!
    usage: /<command>
  rickroll:
    description: Will never ever give up any player
    usage: /<command> player
  loadedworlds:
    description: List all currently loaded worlds.
    usage: /<command>
permissions:
  dungeon.gencommand:
    description: Allows the usage of /gendungeon
    default: op
  dungeon.loaded:
    description: Allows the usage of /loadedworlds
    default: op
