name: Dungeons
version: '${version}'
main: com.pluginjam.PluginJam
api-version: 1.19
authors: [ HiWhatName, earomc ]
softdepend: [NoteBlockAPI, HolographicDisplays]
depend: [FastAsyncWorldEdit]
description: The more you have, the worse it is
website: https://www.youtube.com/watch?v=dQw4w9WgXcQ
commands:
  summondungeonmob:
    description: Summons a dungeon mob.
    usage: /<command>
  gendungeon:
    description: Used for testing purposes only
    usage: /<command>
  radio:
    description: Perform actions such as toggling the radio
    usage: /<command> toggle,volume
  rickroll:
    description: Will never ever give up any player
    usage: /<command> player
  loadedworlds:
    description: List all currently loaded worlds.
    usage: /<command>
permissions:
  dungeon.gencommand:
    description: Allows the usage of /gendungeon
    default: op
  dungeon.loaded:
    description: Allows the usage of /loadedworlds
    default: op
  dungeon.summon:
    description: Allows the usage of /summondungeonmob
    default: op
